### ISSUE TITLE
Problem creating geojson

### ISSUE THREAD

**Issue by kovacevski** [LibreDWG/libredwg#977] opened 2024-05-22 07:21 UTC
I have a problem creating geojson from this dwg file.
The command that I am running is: dwgread -O geojson
[output_geojson.json](https://github.com/LibreDWG/libredwg/files/15391061/output_geojson.json)
[test.zip](https://github.com/LibreDWG/libredwg/files/15391062/test.zip)

_Originally posted by @kovacevski in https://github.com/LibreDWG/libredwg/issues/849#issuecomment-2122740242_

**Comment by rurban** [comment] 2024-05-23 05:47
Duplicate of #849
I still don't know how this attributes should appear.

**Closed by rurban** 2024-05-23 05:47 UTC
