### ISSUE TITLE
dwg2dxf output extra newline in dxf file

### ISSUE THREAD

**Issue by eryar** [LibreDWG/libredwg#17] opened 2018-06-10 03:11 UTC
The dwg2dxf output extra newline for every group code and group value in dxf file, so cannot open the DXF file generated by dwg2dxf.

**Comment by rurban** [comment] 2018-06-10 05:02
Thanks for the idea, still working on this one.

**Comment by rurban** [comment] 2018-06-10 16:30
I cannot reproduce that. I emit dos '\r\n', because that's what AutoCAD expects.
I also found one empty line for LTYPE 48, which I fixed with 53643aed23b49a06498dae661f8e9ed3f628c8b7

Can you add a short example what you mean?

**Comment by eryar** [comment] 2018-06-11 14:14
![image](https://user-images.githubusercontent.com/8439181/41236773-854f19c8-6dc4-11e8-97f2-034ff2ef360e.png)

The test.dxf is generated by dwg2dxf, there is a CR, LF for every group code and group value.
These CR,LF should removed.

**Comment by rurban** [comment] 2018-06-11 15:36
Thanks. I think I see CR CR LF there. Right? 
This could be caused by a text write mode to fopen ("w"). Will use "wb" then.

**Comment by rurban** [comment] 2018-06-11 17:09
BTW: If it would be only the the extra \r it would be trivial to fix.
`sed -i 's/\r\r$//' Drawing.dxf`

But the dxf cannot be imported into acad yet, you still have to wait for that, or try --minimal.

**Comment by rurban** [comment] 2018-06-11 17:10
The extra \r on windows should be fixed now.

**Closed by rurban** 2018-06-11 17:10 UTC

**Comment by eryar** [comment] 2018-06-12 01:28
Yes, the extra \r on Windows is fixed now.

And I tried to generate dxf by --minimal option, and cannot open the dxf file in AutoCAD.
I find the output dxf file lack of some import group code and its group value, such as group code 10, 20,

**Comment by rurban** [comment] 2018-06-12 10:23
Thanks, still working on DXF. I added now a second DXF option --low #21, to mimic libdxfrw and other DXF libraries and to get closer to a successful import. Something minor is still missing.

**Comment by eryar** [comment] 2018-06-12 12:16
You are welcome.

That's great!
