### ISSUE TITLE
SVG wrong viewbox

### ISSUE THREAD

**Issue by laien1900** [LibreDWG/libredwg#446] opened 2022-04-25 10:18 UTC
The transformed SVG  file by dwg2SVG.exe is not recognized by browser

**Comment by realiti4** [comment] 2022-04-25 15:21
I am facing a similar issue. I am not sure what I am doing wrong.

**Comment by rurban** [comment] 2022-04-26 04:15
Sorry, but without any reproducer or diagnostics nobody can help you

**Comment by laien1900** [comment] 2022-04-26 05:34
```
	<path id="dwg-object-1073" d="M 546557.818098,-581161.941138 L 546557.818098,-581161.941138 L 546557.818098,-581161.941138 L 546557.818098,-581161.941138 L 546557.818098,-581161.941138 L 546557.818098,-581161.941138 L 546557.818098,-581161.941138 L 546557.818098,-581161.941138 L 546557.818098,-581161.941138 L 546557.818098,-581161.941138 L 546557.818098,-581161.941138 L 546557.818098,-581161.941138"
	      style="fill:none;stroke:black;stroke-width:0.0px" />
```
All the points above are the same value.

**Comment by michal-josef-spacek** [comment] 2022-04-26 09:25
@laien1900 Could you upload example dwg and output svg? (if will be simple, will be better).

**Comment by laien1900** [comment] 2022-04-26 10:22
> @laien1900 Could you upload example dwg and output svg? (if will be simple, will be better).
DWG file upload is not supported, so you need rename jpg as dwg.
![file1](https://user-images.githubusercontent.com/26765814/165278746-c2edb423-6146-4c45-94af-9a9c614470ae.svg)
![Drawing1](https://user-images.githubusercontent.com/26765814/165278871-15665979-39f1-4f8e-a246-583dec4f68f0.jpg)

**Comment by michal-josef-spacek** [comment] 2022-04-26 11:12
@laien1900 I couldn't read attachment. The best way is gzip/zip files and upload to issue.

**Comment by michal-josef-spacek** [comment] 2022-04-26 11:13
@laien1900 ah, i have files (from email notification).

**Comment by rurban** [comment] 2023-02-10 07:11
Either a duplicate of #523 (wrong viewbox) or missing support for curves and splines #520

**Closed by rurban** 2023-02-10 07:11 UTC
