### ISSUE TITLE
The exported SVG lost its original color

### ISSUE THREAD

**Issue by wangxw0820** [LibreDWG/libredwg#331] opened 2021-04-08 03:43 UTC
I exported DWG to SVG and found that it lost the original color

**Comment by abenson** [comment] 2021-04-08 04:32
Duplicate of #328?

**Comment by rurban** [comment] 2021-04-08 14:13
Can you attach the dwg (zipped)?

**Comment by wangxw0820** [comment] 2021-04-09 00:53
I can't give it to you because of the copyright limitation of DWG, but I know the general reason. It may be that part of the drawing content is in the negative part of the coordinate system

**Comment by wangxw0820** [comment] 2021-04-09 00:53
![image](https://user-images.githubusercontent.com/29654121/114113410-14f49880-9911-11eb-9cce-f78474444405.png)

**Closed** 2021-04-14 10:02 UTC

**Comment by wangxw0820** [comment] 2021-04-14 10:04
There's something wrong with my test
